AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Member Service

Resources:
  MemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: member-service
      CodeUri: .
      Handler: main.handler
      Runtime: python3.11
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_APP_CLIENT_ID: !Ref CognitoAppClientId
      Events:
        MemberApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:*
              Resource: '*'

Parameters:
  DatabaseUrl:
    Type: String
    NoEcho: true
  CognitoUserPoolId:
    Type: String
  CognitoAppClientId:
    Type: String

Outputs:
  ApiURL:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"